-- Run this script in your Supabase SQL Editor to support customer appliance warranties

CREATE TABLE IF NOT EXISTS warranties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g. Television, Washing Machine, Iron Box, Phone, Other
  appliance_name TEXT NOT NULL,
  purchase_date DATE,
  warranty_start_date DATE,
  warranty_duration_months INTEGER,
  receipt_copy TEXT, -- Base64 encoded JPEG
  invoice_copy TEXT, -- Base64 encoded JPEG
  warranty_card_copy TEXT, -- Base64 encoded JPEG
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index on customer_phone for fast queries
CREATE INDEX IF NOT EXISTS idx_warranties_customer_phone ON warranties(customer_phone);

-- Enable Row Level Security (RLS)
ALTER TABLE warranties ENABLE ROW LEVEL SECURITY;

-- Create policies to allow client operations (since we are on a client-integrated flow)
CREATE POLICY "Allow public select access" ON warranties FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON warranties FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON warranties FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access" ON warranties FOR DELETE USING (true);
