-- Run this script in your Supabase SQL Editor to support customer accounts

-- 1. Create the 'customers' table
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT,
  phone TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create index on phone and email for ultra-fast auth queries
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);

-- 3. Enable Row Level Security (RLS) to silence security warnings
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- 4. Set public access policies so client APIs can read and register accounts
CREATE POLICY "Allow public read access" ON customers FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON customers FOR INSERT WITH CHECK (true);

