-- Run this script in your Supabase SQL Editor to support blog comments and reactions

-- 1. Create the 'blog_comments' table
CREATE TABLE IF NOT EXISTS blog_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_slug TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL,
  author_role TEXT NOT NULL CHECK (author_role IN ('customer', 'pro')),
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the 'blog_comment_reactions' table to track likes/dislikes
CREATE TABLE IF NOT EXISTS blog_comment_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id BIGINT REFERENCES blog_comments(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL,
  user_role TEXT NOT NULL CHECK (user_role IN ('customer', 'pro')),
  reaction_type TEXT NOT NULL CHECK (reaction_type IN ('like', 'dislike')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(comment_id, user_email)
);

-- 3. Enable Row Level Security (RLS) for production security
ALTER TABLE blog_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_comment_reactions ENABLE ROW LEVEL SECURITY;

-- 4. Set public access policies for 'blog_comments'
CREATE POLICY "Allow public read comments" ON blog_comments FOR SELECT USING (true);
CREATE POLICY "Allow public insert comments" ON blog_comments FOR INSERT WITH CHECK (true);

-- 5. Set public access policies for 'blog_comment_reactions'
CREATE POLICY "Allow public read reactions" ON blog_comment_reactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert reactions" ON blog_comment_reactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update reactions" ON blog_comment_reactions FOR UPDATE USING (true);
CREATE POLICY "Allow public delete reactions" ON blog_comment_reactions FOR DELETE USING (true);

