-- Run this entire script in your Supabase SQL Editor

-- 1. Create the 'profiles' table
CREATE TABLE profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID, -- For future Supabase Auth integration
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  trade TEXT NOT NULL,
  experience TEXT,
  location TEXT,
  verified BOOLEAN DEFAULT false,
  avatar TEXT,
  about TEXT,
  skills TEXT[], -- Array of strings
  portfolio TEXT[], -- Array of strings (image URLs)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the 'reviews' table
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pro_id BIGINT REFERENCES profiles(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create the 'leads' table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pro_id BIGINT REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  task TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Turn off Row Level Security (RLS) temporarily so we can easily read/write during development
-- WARNING: In a production app, you should enable RLS and set proper policies.
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;

-- Insert a dummy profile so the site doesn't look empty
INSERT INTO profiles (slug, name, trade, experience, location, verified, avatar, about, skills, portfolio)
VALUES (
  'ram-singh', 
  'Ram Singh', 
  'Carpenter', 
  '12 Years', 
  'Bangalore South', 
  true, 
  'https://i.pravatar.cc/150?u=ram-singh', 
  'Expert in modular kitchen fitting, wardrobe design, and antique furniture repair. Fast and reliable service.', 
  ARRAY['Modular Kitchen', 'Wardrobes', 'Wood Polishing', 'Door Fitting'], 
  ARRAY['https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=500&q=80', 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=500&q=80']
);

-- Insert a dummy review for Ram
INSERT INTO reviews (pro_id, author, rating, text)
VALUES (
  (SELECT id FROM profiles WHERE slug = 'ram-singh'), 
  'Anita S.', 
  5, 
  'Ram did an amazing job with our kitchen cabinets. Highly recommended!'
);
