-- Supabase Migration: Blog Database & Storage Setup for CarpenterWala
-- Run this entire script in your Supabase SQL Editor (Dashboard > SQL Editor)

-- ==============================================================================
-- 1. Create the `blogs` Table
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  meta_title TEXT,
  meta_description TEXT,
  excerpt TEXT,
  category TEXT NOT NULL DEFAULT 'How to',
  author TEXT DEFAULT 'Rajesh Sharma',
  date TEXT NOT NULL,
  read_time TEXT DEFAULT '7 min read',
  image_url TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft', 'published', 'archived')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 2. Indexes for Query Optimization & Routing
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_blogs_slug ON public.blogs(slug);
CREATE INDEX IF NOT EXISTS idx_blogs_category ON public.blogs(category);
CREATE INDEX IF NOT EXISTS idx_blogs_status ON public.blogs(status);
CREATE INDEX IF NOT EXISTS idx_blogs_created_at ON public.blogs(created_at DESC);

-- ==============================================================================
-- 3. Automatic `updated_at` Timestamp Trigger
-- ==============================================================================
CREATE OR REPLACE FUNCTION update_blogs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_blogs_updated_at ON public.blogs;
CREATE TRIGGER trigger_blogs_updated_at
BEFORE UPDATE ON public.blogs
FOR EACH ROW EXECUTE FUNCTION update_blogs_updated_at();

-- ==============================================================================
-- 4. Row Level Security (RLS)
-- ==============================================================================
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Allow public read access to published blogs (for Next.js SSG / ISR / readers)
DROP POLICY IF EXISTS "Allow public read access for published blogs" ON public.blogs;
CREATE POLICY "Allow public read access for published blogs"
ON public.blogs FOR SELECT
USING (status = 'published');

-- Allow service role full administrative access (for automated scripts / publishing pipeline)
DROP POLICY IF EXISTS "Allow service role full access to blogs" ON public.blogs;
CREATE POLICY "Allow service role full access to blogs"
ON public.blogs FOR ALL
USING (auth.role() = 'service_role');

-- Allow anon key write for development/fallback if service role is not configured
DROP POLICY IF EXISTS "Allow anon upsert for development" ON public.blogs;
CREATE POLICY "Allow anon upsert for development"
ON public.blogs FOR ALL
USING (true)
WITH CHECK (true);

-- ==============================================================================
-- 5. Supabase Storage Setup: `blog-images` Bucket
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('blog-images', 'blog-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policy: Anyone can view blog images publicly
DROP POLICY IF EXISTS "Public blog images are viewable by everyone" ON storage.objects;
CREATE POLICY "Public blog images are viewable by everyone"
ON storage.objects FOR SELECT
USING (bucket_id = 'blog-images');

-- Storage Policy: Allow upload to blog-images bucket
DROP POLICY IF EXISTS "Allow uploads to blog-images bucket" ON storage.objects;
CREATE POLICY "Allow uploads to blog-images bucket"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'blog-images');

DROP POLICY IF EXISTS "Allow updates to blog-images bucket" ON storage.objects;
CREATE POLICY "Allow updates to blog-images bucket"
ON storage.objects FOR UPDATE
USING (bucket_id = 'blog-images');
