import Link from 'next/link';

export const metadata = {
  title: "Privacy Policy | Carpenterwala",
  description: "Learn how Carpenterwala collects, safeguards, and uses your information.",
};

export default function PrivacyPolicy() {
  return (
    <div className="container animate-fade-in" style={{ padding: "4rem 2rem", maxWidth: "900px" }}>
      <h1 className="text-gradient" style={{ fontSize: "3rem", marginBottom: "2rem" }}>Privacy Policy</h1>

      <div className="glass" style={{ padding: "3rem", lineHeight: "1.8", color: "rgba(255,255,255,0.9)" }}>
        <p style={{ marginBottom: "2rem", fontSize: "1.1rem", opacity: 0.8 }}>
          <strong>Effective date: May 11, 2026</strong>
        </p>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>1. Introduction</h2>
          <p>
            Welcome to <strong>Carpenterwala Marketplace</strong>.
          </p>
          <p>
            Carpenterwala Marketplace (“us”, “we”, or “our”) operates <strong>https://carpenterwala.com</strong> (hereinafter referred to as “Service”).
            Our Privacy Policy governs your visit to our website and explains how we collect, safeguard, and disclose information that results from your use of our Service.
          </p>
          <p>
            We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
          </p>
        </section>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>2. Definitions</h2>
          <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: "1rem" }}>
            <li><strong>SERVICE</strong> means the https://carpenterwala.com website operated by Carpenterwala Marketplace.</li>
            <li><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data.</li>
            <li><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself.</li>
            <li><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</li>
            <li><strong>DATA CONTROLLER</strong> means a natural or legal person who determines the purposes for which and the manner in which any personal data are processed.</li>
          </ul>
        </section>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>3. Information Collection and Use</h2>
          <p>
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
          <h3 style={{ marginTop: "1.5rem", marginBottom: "0.5rem" }}>Types of Data Collected</h3>
          <p><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information such as:</p>
          <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
        </section>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>4. Use of Data</h2>
          <p>Carpenterwala Marketplace uses the collected data for various purposes:</p>
          <ul style={{ paddingLeft: "1.5rem", marginTop: "0.5rem" }}>
            <li>To provide and maintain our Service;</li>
            <li>To notify you about changes to our Service;</li>
            <li>To allow you to participate in interactive features of our Service;</li>
            <li>To provide customer support;</li>
            <li>To gather analysis or valuable information so that we can improve our Service;</li>
            <li>To monitor the usage of our Service;</li>
            <li>To detect, prevent and address technical issues;</li>
          </ul>
        </section>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>5. Security of Data</h2>
          <p>
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.
            While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
        </section>

        <section style={{ marginBottom: "3rem" }}>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>6. Your Data Protection Rights</h2>
          <p>
            We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <strong>contact@carpenterwala.com</strong>.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: "1.75rem", marginBottom: "1rem", color: "var(--primary)" }}>7. Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <ul style={{ listStyle: "none", marginTop: "0.5rem" }}>
            <li>By email: <strong>contact@carpenterwala.com</strong></li>
            <li>By visiting this page on our website: <Link href="/contact" style={{ color: "var(--accent)" }}>Contact Us</Link></li>
          </ul>
        </section>
      </div>

      <div style={{ marginTop: "3rem", textAlign: "center" }}>
        <Link href="/" className="btn btn-secondary">
          Back to Home
        </Link>
      </div>
    </div>
  );
}
