-- =========================================================================
-- Migration 01: Core Application Schema
-- Tables: profiles, reviews, leads, customers, warranties, blog_comments
-- =========================================================================

-- 1. PROFILES TABLE (Professionals & Handymen)
CREATE TABLE IF NOT EXISTS public.profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  trade TEXT NOT NULL,
  experience TEXT,
  location TEXT,
  full_address TEXT,
  about TEXT,
  skills TEXT[] DEFAULT '{}',
  portfolio TEXT[] DEFAULT '{}',
  avatar TEXT,
  pending_avatar TEXT,
  
  -- KYC Document References (Storage paths / legacy Base64)
  aadhaar_front TEXT,
  aadhaar_back TEXT,
  pan_front TEXT,
  pan_back TEXT,
  voter_driving_front TEXT,
  voter_driving_back TEXT,
  police_verification TEXT,
  
  -- Verification & Onboarding Flow
  verified BOOLEAN DEFAULT false,
  onboarding_completed BOOLEAN DEFAULT false,
  onboarding_step INT DEFAULT 1,
  accepting_leads BOOLEAN DEFAULT true,
  rejection_reason JSONB DEFAULT NULL,
  
  rating NUMERIC DEFAULT 5.0,
  reviews_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_profiles_slug ON public.profiles (slug);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON public.profiles (phone);
CREATE INDEX IF NOT EXISTS idx_profiles_trade_location ON public.profiles (trade, location);

-- 2. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pro_id BIGINT REFERENCES public.profiles(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reviews_pro_id ON public.reviews (pro_id);

-- 3. LEADS TABLE (Customer service requests)
CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pro_id BIGINT REFERENCES public.profiles(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  task TEXT NOT NULL,
  address TEXT,
  status TEXT DEFAULT 'pending', -- pending, accepted, completed, cancelled
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leads_pro_id ON public.leads (pro_id);
CREATE INDEX IF NOT EXISTS idx_leads_customer_phone ON public.leads (customer_phone);

-- 4. CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT,
  email TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers (phone);

-- 5. WARRANTIES TABLE (Appliance warranty locker)
CREATE TABLE IF NOT EXISTS public.warranties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_phone TEXT NOT NULL,
  category TEXT NOT NULL,
  appliance_name TEXT NOT NULL,
  purchase_date DATE,
  warranty_start_date DATE,
  warranty_duration_months INT,
  
  -- Document storage paths / legacy Base64
  receipt_copy TEXT,
  invoice_copy TEXT,
  warranty_card_copy TEXT,
  
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_warranties_customer_phone ON public.warranties (customer_phone);

-- 6. BLOG COMMENTS TABLE
CREATE TABLE IF NOT EXISTS public.blog_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_slug TEXT NOT NULL,
  parent_id BIGINT REFERENCES public.blog_comments(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  author_email TEXT,
  comment_text TEXT NOT NULL,
  likes_count INT DEFAULT 0,
  dislikes_count INT DEFAULT 0,
  status TEXT DEFAULT 'approved', -- approved, pending, flagged
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_blog_comments_slug ON public.blog_comments (blog_slug);
