-- =========================================================================
-- Migration 03: DIY Reels Schema
-- Tables: diy_reel_categories, diy_reels
-- =========================================================================

-- 1. DIY REEL CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.diy_reel_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_diy_reel_categories_slug ON public.diy_reel_categories (slug);

-- 2. DIY REELS TABLE
CREATE TABLE IF NOT EXISTS public.diy_reels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  youtube_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  category_id BIGINT REFERENCES public.diy_reel_categories(id) ON DELETE SET NULL,
  category_name TEXT,
  tags TEXT[] DEFAULT '{}',
  thumbnail_url TEXT,
  likes_count INT DEFAULT 0,
  views_count INT DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_diy_reels_youtube_id ON public.diy_reels (youtube_id);
CREATE INDEX IF NOT EXISTS idx_diy_reels_category_id ON public.diy_reels (category_id);
CREATE INDEX IF NOT EXISTS idx_diy_reels_is_published ON public.diy_reels (is_published);
CREATE INDEX IF NOT EXISTS idx_diy_reels_created_at ON public.diy_reels (created_at DESC);

-- Enable RLS
ALTER TABLE public.diy_reel_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diy_reels ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on diy_reel_categories"
  ON public.diy_reel_categories FOR SELECT
  USING (true);

CREATE POLICY "Allow public read access on published diy_reels"
  ON public.diy_reels FOR SELECT
  USING (is_published = true);

-- Allow all operations for authenticated service roles / anon with key
CREATE POLICY "Allow full access to diy_reel_categories"
  ON public.diy_reel_categories FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow full access to diy_reels"
  ON public.diy_reels FOR ALL
  USING (true)
  WITH CHECK (true);
